version: '3'  # версия Docker Compose

services:  # список сервисов, которые будут запущены вместе при запуске приложения
  backend:  # сервис для бэкенда приложения
    image: nlp_back  # название образа для бэкенда
    healthcheck:  # параметры проверки состояния контейнера
      test: ["CMD", "curl", "--fail", "localhost:8000/test"] # проверка доступности "localhost:8000/test"
      interval: 5s  # интервал между попытками проверки состояния
      timeout: 5s  # время ожидания для выполнения проверки
      retries: 3  # ККоличество неудачных попыток проверки состояния перед тем, как сервис считается неработоспособным
    
  nginx: # сервис для NGINX, выполняющего роль обратного прокси
    image: nlp_nginx # название образа для NGINX
    ports: 
      - 80:80  # порт, проброшенный из контейнера на хост
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # том (volume), который будет смонтирован в контейнер в режиме только для чтения
    depends_on:
      backend:
        condition: service_healthy  # NGINX будет запущен только после того, как сервис backend пройдет проверку состояния
